# The Useful Packages for macOS Systems
[packages.darwin]
brews = [
  "aria2",
  "asdf",
  "bat",
  "croc",
  "curl",
  "dua-cli",
  "eza",
  "fd",
  "fzf",
  "findutils",
  "gh",
  "git",
  "git-lfs",
  "neovim",
  "ripgrep",
  "thefuck",
  "tmux",
  "zoxide"
]

casks = [
  "font-hack-nerd-font",
  "iterm2",
  "orbstack"
]

# The Useful Packages for Linux Systems
[packages.linux]
packages = [
  "aria2",
  "bat",
  "curl",
  "exa",
  "eza",
  "fd",
  "fd-find",
  "fzf",
  "gh",
  "git",
  "git-lfs",
  "net-tools",
  "plocate",
  "ripgrep",
  "tmux",
  "zoxide"
]

cmd = [
  ["asdf", "asdf", "git clone https://github.com/asdf-vm/asdf.git ~/.asdf 2>/dev/null || echo \"Repo already exists. Skipping clone.\""],
  ["croc", "croc", "curl https://getcroc.schollz.com | bash"],
  ["dua-cli", "dua", "curl -LSfs https://raw.githubusercontent.com/Byron/dua-cli/master/ci/install.sh | sh -s -- --git Byron/dua-cli --target x86_64-unknown-linux-musl --crate dua --tag v2.29.0"],
]

miniPackages = [
  "bat",
  "curl",
  "exa",
  "eza",
  "fzf",
  "net-tools",
  "ripgrep",
  "tmux",
  "zoxide"
]

miniCmd = [
  ["croc", "croc", "curl https://getcroc.schollz.com | bash"],
]