# The Useful Packages for macOS Systems
[packages.darwin]
brews = [
  "aria2",
  "asdf",
  "bat",
  "btop",
  "croc",
  "curl",
  "dua-cli",
  "eza",
  "fd",
  "fzf",
  "findutils",
  "gh",
  "git",
  "git-lfs",
  "git-delta",
  "lazygit",
  "navi",
  "neovim",
  "nnn",
  "ripgrep",
  "thefuck",
  "tmux",
  "tldr",
  "zoxide"
]

casks = [
  "font-hack-nerd-font",
  # "iterm2",
  # "orbstack"
]

miniPackages = [
  "bat",
  "curl",
  "eza",
  "fzf",
  "git",
  "git-delta",
  "ripgrep",
  "tmux",
  "zoxide"
]

# The Useful Packages for Linux Systems
[packages.linux]
packages = [
  "aria2",
  "bat",
  "curl",
  "exa",
  "eza",
  "fd",
  "fd-find",
  "fzf",
  "gh",
  "git",
  "git-lfs",
  "git-delta",
  "lazygit",
  "net-tools",
  "nnn",
  "plocate",
  "ripgrep",
  "tmux",
  "zoxide"
]

cmd.amd64 = [
  ["asdf", "asdf", "mkdir -p $HOME/.local/bin; cd $HOME/.local/bin; curl -L -o asdf-v0.18.0-linux-amd64.tar.gz https://github.com/asdf-vm/asdf/releases/download/v0.18.0/asdf-v0.18.0-linux-amd64.tar.gz && tar -xvf asdf-v0.18.0-linux-amd64.tar.gz && rm -f asdf-v0.18.0-linux-amd64.tar.gz && cd -"],
  ["croc", "croc", "curl https://getcroc.schollz.com | bash"],
]

cmd.arm64 = [
  ["asdf", "asdf", "mkdir -p $HOME/.local/bin; cd $HOME/.local/bin; curl -L -o asdf-v0.18.0-linux-arm64.tar.gz https://github.com/asdf-vm/asdf/releases/download/v0.18.0/asdf-v0.18.0-linux-arm64.tar.gz && tar -xvf asdf-v0.18.0-linux-arm64.tar.gz && rm -f asdf-v0.18.0-linux-arm64.tar.gz && cd -"],
  ["croc", "croc", "curl https://getcroc.schollz.com | bash"],
]

miniPackages = [
  "bat",
  "curl",
  "exa",
  "eza",
  "fzf",
  "git-delta",
  "net-tools",
  "ripgrep",
  "tmux",
  "zoxide"
]

miniCmd = [
  ["croc", "croc", "curl https://getcroc.schollz.com | bash"],
]